Libraries

In [2]:
# import basic libraries
import os
from glob import glob

from pathlib import Path
import pandas as pd 
import matplotlib.pyplot as plt

Load data

In [3]:
# set paths to train and test image datasets

train_path = '../data/raw/train_images/'
test_path = '../data/raw//test_images/'

In [4]:
## number of images in train and test datasets

# sort the image file names of the train and test image files as lists 
train_fns = sorted(glob(train_path + '*.jpg'))
print('There are {} images in the train set.'.format(len(train_fns)))

test_fns = sorted(glob(test_path + '*.jpg'))
print('There are {} images in the test set.'.format(len(test_fns)))

There are 5546 images in the train set.
There are 3698 images in the test set.

In [6]:
# load dataframe with train labels

train_df = pd.read_csv(r"../data/raw/train.csv/train.csv")
train_df.head(15)

           Image_Label                                      EncodedPixels
0     0011165.jpg_Fish  20056 257 20440 257 20824 257 21208 257 21592 ...
1   0011165.jpg_Flower  102135 1 102245 275 102629 275 103013 275 1033...
2   0011165.jpg_Gravel                                                NaN
3    0011165.jpg_Sugar                                                NaN
4     002be4f.jpg_Fish  17668 241 18051 242 18435 242 18819 242 19203 ...
5   002be4f.jpg_Flower  100850 142 101234 142 101618 142 102002 142 10...
6   002be4f.jpg_Gravel                                                NaN
7    002be4f.jpg_Sugar  5074 96 5458 96 5842 96 6226 96 6610 96 6994 9...
8     0031ae9.jpg_Fish  579 190 963 190 1347 190 1731 190 2115 190 249...
9   0031ae9.jpg_Flower  178 193 562 193 946 193 1330 193 1714 193 2098...
10  0031ae9.jpg_Gravel                                                NaN
11   0031ae9.jpg_Sugar  49583 107 49967 107 50351 107 50735 107 51119 ...
12    0035239.jpg_Fish                                                NaN
13  0035239.jpg_Flower  7684 127 8068 127 8452 127 8836 127 9220 127 9...
14  0035239.jpg_Gravel  5267 104 5651 104 6035 104 6419 104 6803 104 7...

In [7]:
train_df.shape

(22184, 2)

In [8]:
# 1. Number of rows
print("Number of rows in train_df is:", len(train_df))

Number of rows in train_df is: 22184

In [9]:
# 2. Type of each variable
print("Variable types:\n")
print(train_df.dtypes)

Variable types:

Image_Label      str
EncodedPixels    str
dtype: object

##### 3. Description of the table's columns

"Image_Label": "Image ID and format combined with the cloud class.",

"EncodedPixels": "Encoded cloud mask. It contains the index number of the starting pixel masked as cloud and also the number of themcloudy pixels. For example "20056 257" means that the index of the starting cloud pixel is 20056 and by next 57 pixels are encoded as cloudy pixel in the format of fish. 
Moreover, NaN value means no cloud for that class."

##### 4. Availability of the variable beforehand????

For `EncodedPixels`:

No. This variable is available in the training data, but it will not be available before prediction in real use. It is the target mask that the model must predict for new cloud images.

In [12]:
# Check duplicates
train_df.duplicated().sum()

np.int64(0)

In [13]:
# Split Image_Label into image name and class
train_df["Image"] = train_df["Image_Label"].apply(lambda x: x.split("_")[0])
train_df["Class"] = train_df["Image_Label"].apply(lambda x: x.split("_")[1])

In [14]:
train_df

,Image_Label,EncodedPixels,Image,Class
0,0011165.jpg_Fish,20056 257 20440 257 20824 257 21208 257 21592 ...,0011165.jpg,Fish
1,0011165.jpg_Flower,102135 1 102245 275 102629 275 103013 275 1033...,0011165.jpg,Flower
2,0011165.jpg_Gravel,NaN,0011165.jpg,Gravel
3,0011165.jpg_Sugar,NaN,0011165.jpg,Sugar
4,002be4f.jpg_Fish,17668 241 18051 242 18435 242 18819 242 19203 ...,002be4f.jpg,Fish
...,...,...,...,...
22179,ffd6680.jpg_Sugar,NaN,ffd6680.jpg,Sugar
22180,ffea4f4.jpg_Fish,NaN,ffea4f4.jpg,Fish
22181,ffea4f4.jpg_Flower,90038 185 90422 185 90806 185 91190 185 91574 ...,ffea4f4.jpg,Flower
22182,ffea4f4.jpg_Gravel,NaN,ffea4f4.jpg,Gravel
22183,ffea4f4.jpg_Sugar,NaN,ffea4f4.jpg,Sugar

In [15]:
# Check class distribution
train_df["Class"].value_counts()

Class
Fish      5546
Flower    5546
Gravel    5546
Sugar     5546
Name: count, dtype: int64

In [ ]:
mask_counts = train_df.groupby("Class")["EncodedPixels"].apply(lambda x: x.notna().sum())
mask_counts = train_df.groupby("Class")["EncodedPixels"].apply(lambda x: x.notna().sum())
mask_percent = (mask_counts / train_df["Image"].nunique() * 100).round(2)
mask_percent
mask_percent

SyntaxError: invalid decimal literal (440347293.py, line 2)

In [10]:
## 5. missing values rate in %
missing_rate = (train_df.isnull().sum()) / len(train_df) * 100
print(missing_rate)

Image_Label       0.000000
EncodedPixels    46.646232
dtype: float64

##### 6. Management of missing values